# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Day05-MosaicLayout' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Day05-MosaicLayout

  pod 'SwiftyJSON', '~> 5.0.1'
  pod 'FMMosaicLayout'

  target 'Day05-MosaicLayoutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Day05-MosaicLayoutUITests' do
    # Pods for testing
  end

end
